### ISSUE TITLE
Setup code coverage

### ISSUE THREAD

**Issue by Sean-Der** [maxmcd/webtty#34]
We just need to add the following to our `go test`

```
-coverprofile=cover.out -covermode=atomic
```

Then use this action after the tests run
```
      - uses: codecov/codecov-action@v1
        with:
          file: ./cover.out
          name: codecov-umbrella
          fail_ci_if_error: true
          flags: go
```
